### PR TITLE
feat: add `host` option

### LINKED ISSUE #3: doesn't detect collisions on macos
when I have a server running on port 3000 and call `getPort(3000)` it returns `3000` rather than detecting a port collision

it defaults to these server options:
```
console.log(server.address())
// { address: '::', family: 'IPv6', port: 3000 }
```

### PR DESCRIPTION
**Pull request by mrazauskas**
At the moment `getPort()` always checks ports on `0.0.0.0`.

Issue: if some app already listens on `localhost:3000` (rather usual in `dev` environment), `getPort(3000)` will return `3000`. It simply checked if `0.0.0.0:3000` is free. (Would be good to check, but it sounds similar to issue #3.)

Solution: we need a possibility to check `host` and `port` combination. In similar situation like above `getPort({ host: 'localhost' })` would return `4000`.

What should be the default value of the `host` option? Perhaps the same, which is used by [`listhen`](https://github.com/unjs/listhen/blob/9f321ab9b2fb88299893db363c11d779eb4bfc4f/src/index.ts#L49)?

### CODE REVIEW

**Review by pi0 — APPROVED** [review]
Thanks!

**Comment by pi0** [comment]
> What should be the default value of the host option? Perhaps the same, which is used by listhen?

I think we might ideally support host as array to check both 127.0.0.1 (internal) and 0.0.0.0 (external)

**Comment by pi0** [comment]
`default port is in use` is failing in wsl2 (blocking on localhost does not blocks on 0.0.0.0)

**Comment by mrazauskas** [comment]
Hosts array as default value. That’s really smart! I will try it out.

**Pull request merged**
